version: 0.2

phases:
  pre_build:
    commands:
    - echo Installing pip
    - wget https://bootstrap.pypa.io/get-pip.py
    - python --version
    - python get-pip.py --user
    - python -m pip install mkdocs --user
  build:
    commands:
    - echo Building MkDocs Site
    - python -m mkdocs build
    - aws s3 sync ./site s3://path/subdirectory
  post_build:
    commands:
    - echo MkDocs Site Deployed Successfully!

